version: '3.8'

services:

  koha:
    build:
      context: .
    container_name: koha
    cap_add:
      - SYS_NICE
      - DAC_READ_SEARCH
    depends_on:
      - koha-db
    environment:
      DB_HOST: koha-db
      DB_ROOT_PASSWORD: secret
      KOHA_DB_HOST: koha-db
      KOHA_DB_USER: koha_user
      KOHA_DB_PASS: koha_password
      KOHA_DB_NAME: koha_defaultlibraryname
      DOMAIN: .asies.org.gt
      KOHA_TRANSLATE_LANGUAGES: "ca-ES"
      INTRAPORT: 8001
      INTRAPREFIX: library
      INTRASUFFIX: .admin
      OPACPREFIX: library
    ports:
      - "8001:80"
      - "8081:8080"

  koha-db:
    container_name: koha-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: koha_defaultlibraryname
      MYSQL_USER: koha_user
      MYSQL_PASSWORD: koha_password
    # Newer versions not working
    image: mariadb:10.3

  memcached:
    command: memcached -m 64m
    container_name: memcached
    image: memcached
    ports:
      - "11311:11211"
